### ISSUE TITLE
Renaming of oemof repositories

### ISSUE THREAD

**Issue by uvchik** [oemof/organisation#21]
We do have repositories named `examples` and `sandbox` in our organisation. I would like do add `oemof_` because clones or imports would look more specific.

`from sandbox import something` vs. `from oemof_sandbox import something`

And if you clone the examples of oemof the folder name would be rather `oemof_examples` than just `examples`.

I would **not** do this for the `feedinlib` or the `demandlib` because these names are already quite specific.

**Comment by uvchik** [comment]
@oemof/oemof-developer-group

**Comment by ckaldemeyer** [comment]
> We do have repositories named examples and sandbox in our organisation. I would like do add oemof_ because clones or imports would look more specific.
> 
> from sandbox import something vs. from oemof_sandbox import something
> 
> And if you clone the examples of oemof the folder name would be rather oemof_examples than just examples.
> 
> I would not do this for the feedinlib or the demandlib because these names are already quite specific.

I have created the sandbox repository for some heat modelling literature overview (in the wiki) but it could be deleted as I am not using it..

**Comment by c-moeller** [comment]
I would like to go through the literature wiki once, so please do not delete it. Otherwise we could rename it to heat_sandbox or something if @ckaldemeyer doesn't need it anymore.

**Comment by c-moeller** [comment]
... or oemof_heat_sandbox

**Comment by uvchik** [comment]
@c-moeller I would prefer `oemof_sandbox` and `oemof_examples`. You could add a heat folder within the repository
@ckaldemeyer I would like to keep the sandbox. It's a good place to try out new stuff together.

@oemof/oemof-developer-group As most people do not care about the sandbox. Who does **not** want to rename `examples` to `oemof_examples`.

**Comment by simnh** [comment]
@all: I do not care about the naming...just don't delete the examples ;)

**Comment by uvchik** [comment]
Done

**Comment by c-moeller** [comment]
I'm confused. The wiki in oemof_examples is now empty. And the oemof_sandbox with the wiki still exists:
https://github.com/oemof/oemof_sandbox/wiki/Overview-of-heat-technology-literature

**Comment by uvchik** [comment]
oemof_sandbox: Share experimental stuff with others.

oemof_examples: The official oemof examples repository. Replacing the internal example folders and open it to everybody who want to share an example.

**Comment by c-moeller** [comment]
Thanks :smile:
